#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "ssd1366.h"
#include "font8x8_basic.h"

#define tag "SSD1306"


/**
 * SSD1306_init()
 * Initialise the display and switch it on.
 */
void SSD1306_init() {
  i2cTransaction_t trans;

  trans.type = I2C_TX;
  trans.devAddr=OLED_I2C_ADDRESS;
  trans.reg = OLED_CONTROL_BYTE_CMD_STREAM;
  trans.nData = 5;
  trans.wait = true;
  trans.data[0] = OLED_CMD_SET_CHARGE_PUMP;
  trans.data[1] = 0x14;
  trans.data[2] = OLED_CMD_SET_SEGMENT_REMAP;
  trans.data[3] = OLED_CMD_SET_COM_SCAN_MODE;
  trans.data[4] = OLED_CMD_DISPLAY_ON;
  i2cRunTransaction(&trans);
  if (trans.retVal) {
    printf("ssd1306: ERROR - Error in SSD1306_init\n");
  }
  else {
    printf("ssd1306: Initialised OK\n");
  }
  SSD1306_clearDisplay();      
}

/**
 * SSD1306_clearDisplay()
 * clear the display.
 */
void SSD1306_clearDisplay() {
  i2cTransaction_t trans;

  for (uint8_t lineNo=0; lineNo<8; lineNo++) {
    trans.type = I2C_TX;
    trans.devAddr=OLED_I2C_ADDRESS;
    trans.reg = OLED_CONTROL_BYTE_CMD_SINGLE;
    trans.nData = 1;
    trans.wait = true;
    trans.data[0] = 0xB0 | lineNo;
    i2cRunTransaction(&trans);
    if (trans.retVal) {
      printf("ssd1306: ERROR - Error in SSD1306_clearDisplay - 1\n");
    }

    trans.type = I2C_TX;
    trans.devAddr=OLED_I2C_ADDRESS;
    trans.reg = OLED_CONTROL_BYTE_DATA_STREAM;
    trans.nData = 128;
    trans.wait = true;
    for(int i=0;i<128;i++)
      trans.data[i] = 0;
    i2cRunTransaction(&trans);
    if (trans.retVal) {
      printf("ssd1306: ERROR - Error in SSD1306_clearDisplay - 2\n");
    }
    printf("ssd1306:  SSD1306_clearDisplay() Complete\n");
  }
}

/**
 * SSD1306_displayText(char* text)
 * Writes the given string to the display, respecting '\n' as a new line character.
 */
void SSD1306_displayText(char *text) {
  i2cTransaction_t trans;
  uint8_t cur_page = 0;
  
  trans.type = I2C_TX;
  trans.devAddr=OLED_I2C_ADDRESS;
  trans.reg = OLED_CONTROL_BYTE_CMD_STREAM;
  trans.nData = 3;
  trans.wait = true;
  trans.data[0] = 0x00;
  trans.data[1] = 0x10;
  trans.data[2] = 0xB0 | cur_page;
  i2cRunTransaction(&trans);
  if (trans.retVal) {
    printf("ssd1306: ERROR - Error in SSD1306_display_text - 1\n");
  }

  for(uint8_t i=0; i<strlen(text);i++) {
    if (text[i] == '\n') {
      cur_page ++;
      trans.type = I2C_TX;
      trans.devAddr=OLED_I2C_ADDRESS;
      trans.reg = OLED_CONTROL_BYTE_CMD_STREAM;
      trans.nData = 3;
      trans.wait = true;
      trans.data[0] = 0x00;
      trans.data[1] = 0x10;
      trans.data[2] = 0xB0 | cur_page;
      i2cRunTransaction(&trans);
      if (trans.retVal) {
	printf("ssd1306: ERROR - Error in SSD1306_display_text - 2\n");
      }
    } else {
      trans.type = I2C_TX;
      trans.devAddr=OLED_I2C_ADDRESS;
      trans.reg = OLED_CONTROL_BYTE_DATA_STREAM;
      trans.nData = 8;
      trans.wait = true;
      for (uint8_t b=0;b<8;b++)
	trans.data[b] = font8x8_basic_tr[(uint8_t)text[i]][b];
      trans.data[2] = 0xB0 | cur_page;
      i2cRunTransaction(&trans);
      if (trans.retVal) {
	printf("ssd1306: ERROR - Error in SSD1306_display_text - 2\n");
      }

    }
  }
      
}

/**
 * SSD1306_init()
 * Initialise the display and switch it on.
 */
void SSD1306_setContrast(uint8_t contrast) {
  i2cTransaction_t trans;

  trans.type = I2C_TX;
  trans.devAddr=OLED_I2C_ADDRESS;
  trans.reg = OLED_CONTROL_BYTE_CMD_STREAM;
  trans.nData = 2;
  trans.wait = true;
  trans.data[0] = OLED_CMD_SET_CONTRAST;
  trans.data[1] = contrast;
  i2cRunTransaction(&trans);
  if (trans.retVal) {
    printf("ssd1306: ERROR - Error in SSD1306_setContrast\n");
  }
}


/**
 * SSD1306_displayBitmap(char *bmp)
 * Displays the 128 byte bitmap *bmp on the screen.
 */
void SSD1306_displayBitmap(char *bmp) {
  i2cTransaction_t trans;

  for (uint8_t blkNo = 0; blkNo<8; blkNo ++) {
    trans.type = I2C_TX;
    trans.devAddr=OLED_I2C_ADDRESS;
    trans.reg = OLED_CONTROL_BYTE_CMD_SINGLE;
    trans.nData = 1;
    trans.wait = true;
    trans.data[0] = 0xB0 | blkNo;
    i2cRunTransaction(&trans);
    if (trans.retVal) {
      printf("ssd1306: ERROR - Error in SSD1306_displayBitmap - 1\n");
    }
    
    trans.type = I2C_TX;
    trans.devAddr=OLED_I2C_ADDRESS;
    trans.reg = OLED_CONTROL_BYTE_DATA_STREAM;
    trans.nData = 128;
    trans.wait = true;
    for(int i=0;i<128;i++)
      trans.data[i] = bmp[i+128*blkNo];
    i2cRunTransaction(&trans);
    if (trans.retVal) {
      printf("ssd1306: ERROR - Error in SSD1306_displayBitmap - 2\n");
    }
  }
}

void task_ssd1306_display_pattern(void *ignore) {
	i2c_cmd_handle_t cmd;

	for (uint8_t i = 0; i < 8; i++) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0xB0 | i, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		for (uint8_t j = 0; j < 128; j++) {
			i2c_master_write_byte(cmd, 0xFF >> (j % 8), true);
		}
		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
	}

	vTaskDelete(NULL);
}





